/* ============================================================
   Dice & Monsters — 5e SRD spell list (for the character sheet)
   ------------------------------------------------------------
   Each entry: n = name, l = level (0 = cantrip), c = classes that
   can cast it. Class keys are lowercase and match srd-data.js.
   Game data from the 5e SRD (CC-licensed). Not exhaustive, but
   covers the common SRD spells through 5th level plus staples above.
   ============================================================ */
(function () {
  'use strict';
  function S(n, l, c) { return { n: n, l: l, c: c }; }
  var B = 'bard', C = 'cleric', D = 'druid', P = 'paladin',
      R = 'ranger', So = 'sorcerer', W = 'warlock', Wz = 'wizard';

  window.SRD_SPELLS = [
    // ---- Cantrips ----
    S('Acid Splash', 0, [So, Wz]),
    S('Chill Touch', 0, [So, W, Wz]),
    S('Dancing Lights', 0, [B, So, Wz]),
    S('Druidcraft', 0, [D]),
    S('Eldritch Blast', 0, [W]),
    S('Fire Bolt', 0, [So, Wz]),
    S('Guidance', 0, [C, D]),
    S('Light', 0, [B, C, So, Wz]),
    S('Mage Hand', 0, [B, So, W, Wz]),
    S('Mending', 0, [B, C, D, So, Wz]),
    S('Message', 0, [B, So, Wz]),
    S('Minor Illusion', 0, [B, So, W, Wz]),
    S('Poison Spray', 0, [D, So, W, Wz]),
    S('Prestidigitation', 0, [B, So, W, Wz]),
    S('Produce Flame', 0, [D]),
    S('Ray of Frost', 0, [So, Wz]),
    S('Resistance', 0, [C, D]),
    S('Sacred Flame', 0, [C]),
    S('Shillelagh', 0, [D]),
    S('Shocking Grasp', 0, [So, Wz]),
    S('Spare the Dying', 0, [C]),
    S('Thaumaturgy', 0, [C]),
    S('True Strike', 0, [B, So, W, Wz]),
    S('Vicious Mockery', 0, [B]),

    // ---- Level 1 ----
    S('Alarm', 1, [R, Wz]),
    S('Animal Friendship', 1, [B, D, R]),
    S('Bane', 1, [B, C]),
    S('Bless', 1, [C, P]),
    S('Burning Hands', 1, [So, Wz]),
    S('Charm Person', 1, [B, D, So, W, Wz]),
    S('Color Spray', 1, [So, Wz]),
    S('Command', 1, [C, P]),
    S('Comprehend Languages', 1, [B, So, W, Wz]),
    S('Create or Destroy Water', 1, [C, D]),
    S('Cure Wounds', 1, [B, C, D, P, R]),
    S('Detect Magic', 1, [B, C, D, P, R, So, Wz]),
    S('Detect Poison and Disease', 1, [C, D, P, R]),
    S('Disguise Self', 1, [B, So, Wz]),
    S('Divine Favor', 1, [P]),
    S('Entangle', 1, [D]),
    S('Expeditious Retreat', 1, [So, W, Wz]),
    S('Faerie Fire', 1, [B, D]),
    S('False Life', 1, [So, Wz]),
    S('Feather Fall', 1, [B, So, Wz]),
    S('Find Familiar', 1, [Wz]),
    S('Fog Cloud', 1, [D, R, So, Wz]),
    S('Goodberry', 1, [D, R]),
    S('Grease', 1, [Wz]),
    S('Guiding Bolt', 1, [C]),
    S('Healing Word', 1, [B, C, D]),
    S('Hellish Rebuke', 1, [W]),
    S('Heroism', 1, [B, P]),
    S("Hunter's Mark", 1, [R]),
    S('Identify', 1, [B, Wz]),
    S('Inflict Wounds', 1, [C]),
    S('Jump', 1, [D, R, So, Wz]),
    S('Longstrider', 1, [B, D, R, Wz]),
    S('Mage Armor', 1, [So, Wz]),
    S('Magic Missile', 1, [So, Wz]),
    S('Protection from Evil and Good', 1, [C, P, W, Wz]),
    S('Purify Food and Drink', 1, [C, D, P]),
    S('Sanctuary', 1, [C]),
    S('Shield', 1, [So, Wz]),
    S('Shield of Faith', 1, [C, P]),
    S('Silent Image', 1, [B, So, Wz]),
    S('Sleep', 1, [B, So, Wz]),
    S('Speak with Animals', 1, [B, D, R]),
    S('Thunderwave', 1, [B, D, So, Wz]),
    S('Unseen Servant', 1, [B, W, Wz]),
    S('Witch Bolt', 1, [So, W, Wz]),

    // ---- Level 2 ----
    S('Acid Arrow', 2, [Wz]),
    S('Aid', 2, [C, P]),
    S('Alter Self', 2, [So, Wz]),
    S('Animal Messenger', 2, [B, D, R]),
    S('Augury', 2, [C]),
    S('Barkskin', 2, [D, R]),
    S('Blindness/Deafness', 2, [B, C, So, Wz]),
    S('Blur', 2, [So, Wz]),
    S('Calm Emotions', 2, [B, C]),
    S('Continual Flame', 2, [C, Wz]),
    S('Darkness', 2, [So, W, Wz]),
    S('Darkvision', 2, [D, R, So, Wz]),
    S('Detect Thoughts', 2, [B, So, Wz]),
    S('Enhance Ability', 2, [B, C, D, So]),
    S('Enlarge/Reduce', 2, [So, Wz]),
    S('Find Traps', 2, [C, D, R]),
    S('Flaming Sphere', 2, [D, Wz]),
    S('Gentle Repose', 2, [C, Wz]),
    S('Gust of Wind', 2, [D, So, Wz]),
    S('Heat Metal', 2, [B, D]),
    S('Hold Person', 2, [B, C, D, So, W, Wz]),
    S('Invisibility', 2, [B, So, W, Wz]),
    S('Knock', 2, [B, So, Wz]),
    S('Lesser Restoration', 2, [B, C, D, P, R]),
    S('Levitate', 2, [So, Wz]),
    S('Locate Object', 2, [B, C, D, P, R, Wz]),
    S('Magic Weapon', 2, [P, Wz]),
    S('Mirror Image', 2, [So, W, Wz]),
    S('Misty Step', 2, [So, W, Wz]),
    S('Moonbeam', 2, [D]),
    S('Pass without Trace', 2, [D, R]),
    S('Prayer of Healing', 2, [C]),
    S('Protection from Poison', 2, [C, D, P, R]),
    S('Ray of Enfeeblement', 2, [W, Wz]),
    S('Scorching Ray', 2, [So, Wz]),
    S('See Invisibility', 2, [B, So, Wz]),
    S('Silence', 2, [B, C, R]),
    S('Spider Climb', 2, [So, W, Wz]),
    S('Spiritual Weapon', 2, [C]),
    S('Suggestion', 2, [B, So, W, Wz]),
    S('Web', 2, [So, Wz]),
    S('Zone of Truth', 2, [B, C, P]),

    // ---- Level 3 ----
    S('Animate Dead', 3, [C, Wz]),
    S('Beacon of Hope', 3, [C]),
    S('Bestow Curse', 3, [B, C, Wz]),
    S('Blink', 3, [So, Wz]),
    S('Call Lightning', 3, [D]),
    S('Clairvoyance', 3, [B, C, So, Wz]),
    S('Counterspell', 3, [So, W, Wz]),
    S('Create Food and Water', 3, [C, P]),
    S('Daylight', 3, [C, D, P, R, So]),
    S('Dispel Magic', 3, [B, C, D, P, So, W, Wz]),
    S('Fear', 3, [B, So, W, Wz]),
    S('Fireball', 3, [So, Wz]),
    S('Fly', 3, [So, W, Wz]),
    S('Gaseous Form', 3, [So, W, Wz]),
    S('Haste', 3, [So, Wz]),
    S('Hypnotic Pattern', 3, [B, So, W, Wz]),
    S('Lightning Bolt', 3, [So, Wz]),
    S('Magic Circle', 3, [C, P, W, Wz]),
    S('Major Image', 3, [B, So, W, Wz]),
    S('Mass Healing Word', 3, [C]),
    S('Meld into Stone', 3, [C, D]),
    S('Nondetection', 3, [B, R, Wz]),
    S('Plant Growth', 3, [B, D, R]),
    S('Protection from Energy', 3, [C, D, R, So, Wz]),
    S('Remove Curse', 3, [C, P, W, Wz]),
    S('Revivify', 3, [C, P]),
    S('Sleet Storm', 3, [D, So, Wz]),
    S('Slow', 3, [So, Wz]),
    S('Speak with Dead', 3, [B, C]),
    S('Spirit Guardians', 3, [C]),
    S('Stinking Cloud', 3, [B, So, Wz]),
    S('Tongues', 3, [B, C, So, W, Wz]),
    S('Vampiric Touch', 3, [W, Wz]),
    S('Water Breathing', 3, [D, R, So, Wz]),
    S('Water Walk', 3, [C, D, R, So]),
    S('Wind Wall', 3, [D, R]),

    // ---- Level 4 ----
    S('Banishment', 4, [C, P, So, W, Wz]),
    S('Blight', 4, [D, So, W, Wz]),
    S('Confusion', 4, [B, D, So, Wz]),
    S('Conjure Woodland Beings', 4, [D, R]),
    S('Control Water', 4, [C, D, Wz]),
    S('Death Ward', 4, [C, P]),
    S('Dimension Door', 4, [B, So, W, Wz]),
    S('Divination', 4, [C]),
    S('Dominate Beast', 4, [D, So]),
    S('Fire Shield', 4, [Wz]),
    S('Freedom of Movement', 4, [B, C, D, R]),
    S('Greater Invisibility', 4, [B, So, Wz]),
    S('Guardian of Faith', 4, [C]),
    S('Ice Storm', 4, [D, So, Wz]),
    S('Locate Creature', 4, [B, C, D, P, R, Wz]),
    S('Polymorph', 4, [B, D, So, Wz]),
    S('Stone Shape', 4, [C, D, Wz]),
    S('Stoneskin', 4, [D, R, So, Wz]),
    S('Wall of Fire', 4, [D, So, Wz]),

    // ---- Level 5 ----
    S('Animate Objects', 5, [B, So, Wz]),
    S('Cloudkill', 5, [So, Wz]),
    S('Commune', 5, [C]),
    S('Cone of Cold', 5, [So, Wz]),
    S('Contact Other Plane', 5, [W, Wz]),
    S('Dispel Evil and Good', 5, [C, P]),
    S('Dominate Person', 5, [B, So, Wz]),
    S('Flame Strike', 5, [C]),
    S('Geas', 5, [B, C, D, P, Wz]),
    S('Greater Restoration', 5, [B, C, D]),
    S('Hold Monster', 5, [B, So, W, Wz]),
    S('Insect Plague', 5, [C, D, So]),
    S('Legend Lore', 5, [B, C, Wz]),
    S('Mass Cure Wounds', 5, [B, C, D]),
    S('Raise Dead', 5, [B, C, P]),
    S('Scrying', 5, [B, C, D, W, Wz]),
    S('Telekinesis', 5, [So, Wz]),
    S('Tree Stride', 5, [D, R]),
    S('Wall of Force', 5, [Wz]),
    S('Wall of Stone', 5, [D, So, Wz]),

    // ---- Higher-level staples (6–9) ----
    S('Heal', 6, [C, D]),
    S('Harm', 6, [C]),
    S('Chain Lightning', 6, [So, Wz]),
    S('Disintegrate', 6, [So, Wz]),
    S('Sunbeam', 6, [D, So, Wz]),
    S('True Seeing', 6, [B, C, So, Wz]),
    S('Finger of Death', 7, [So, W, Wz]),
    S('Plane Shift', 7, [C, D, So, W, Wz]),
    S('Resurrection', 7, [B, C]),
    S('Teleport', 7, [B, So, Wz]),
    S('Fire Storm', 7, [C, D, So]),
    S('Earthquake', 8, [C, D, So]),
    S('Power Word Stun', 8, [B, So, W, Wz]),
    S('Sunburst', 8, [D, So, Wz]),
    S('Foresight', 9, [B, D, W, Wz]),
    S('Mass Heal', 9, [C]),
    S('Meteor Swarm', 9, [So, Wz]),
    S('Power Word Kill', 9, [B, So, W, Wz]),
    S('Time Stop', 9, [So, Wz]),
    S('Wish', 9, [So, Wz])
  ];
})();
